### ISSUE TITLE
Position and Style EndState

### ISSUE THREAD

**Issue by theRemix** [GomaGames/Spawn-RPG#63]
on EndState.hx
position and style elements just like in here
https://github.com/GomaGames/Spawn-RPG/blob/master/dock/ui-mockups/story-win.png
and here
https://github.com/GomaGames/Spawn-RPG/blob/master/dock/ui-mockups/story-lose.png

**Comment by nakaz** [comment]
Created switch state to produce colors for either `WIN` or `LOSE` state. 

Experiencing weird box bug that pushes text to the right. Cannot locate source...

![screen shot 2016-06-26 at 11 30 44 pm](https://cloud.githubusercontent.com/assets/2155125/16375324/983ec936-3bf6-11e6-9253-37fd19c4eba5.png)
